// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__x2jvxpHTNMmlBrwTCqaHw_nXCJhXcw',
    appId: '1:815885700821:web:4a300251741abcfc331c5c',
    messagingSenderId: '815885700821',
    projectId: 'chat-app-6ef72',
    authDomain: 'chat-app-6ef72.firebaseapp.com',
    storageBucket: 'chat-app-6ef72.appspot.com',
    measurementId: 'G-Z9RZNS4QCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8gxId1Vy0BsiRdIstvBySvtF6BWnfOI',
    appId: '1:815885700821:android:2c66ce98b8f882c8331c5c',
    messagingSenderId: '815885700821',
    projectId: 'chat-app-6ef72',
    storageBucket: 'chat-app-6ef72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIdW1u9DNqmGNaHoE04DiREreUHPeId0g',
    appId: '1:815885700821:ios:7fe25154e7ca67ef331c5c',
    messagingSenderId: '815885700821',
    projectId: 'chat-app-6ef72',
    storageBucket: 'chat-app-6ef72.appspot.com',
    iosBundleId: 'com.example.chatAppTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIdW1u9DNqmGNaHoE04DiREreUHPeId0g',
    appId: '1:815885700821:ios:cd33b3273a3e7af4331c5c',
    messagingSenderId: '815885700821',
    projectId: 'chat-app-6ef72',
    storageBucket: 'chat-app-6ef72.appspot.com',
    iosBundleId: 'com.example.chatAppTry.RunnerTests',
  );
}
